In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import nltk
import re
import string
nltk.download('stopwords')
ps = nltk.PorterStemmer()
es_sword = nltk.corpus.stopwords.words("english")


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HOUSSENE\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
#importation du donner
data = pd.read_csv("datasets/Book.csv")
data

index                              title    genre  \
0         0                  Drowned Wednesday  fantasy   
1         1                      The Lost Hero  fantasy   
2         2          The Eyes of the Overworld  fantasy   
3         3                    Magic's Promise  fantasy   
4         4                     Taran Wanderer  fantasy   
...     ...                                ...      ...   
4652   4652                            Hounded  fantasy   
4653   4653  Charlie and the Chocolate Factory  fantasy   
4654   4654                         Red Rising  fantasy   
4655   4655                          Frostbite  fantasy   
4656   4656                           Radiance  fantasy   

                                                summary  
0      Drowned Wednesday is the first Trustee among ...  
1      As the book opens, Jason awakens on a school ...  
2      Cugel is easily persuaded by the merchant Fia...  
3      The book opens with Herald-Mage Vanyel return...  
4      Taran and Gurgi have returned to Caer Dallben...  
...                                                 ...  
4652  Atticus O’Sullivan, last of the Druids, lives ...  
4653  Charlie Bucket's wonderful adventure begins wh...  
4654  "I live for the dream that my children will be...  
4655  Rose loves Dimitri, Dimitri might love Tasha, ...  
4656  The Prince of no value\nBrishen Khaskem, princ...  

[4657 rows x 4 columns]

In [3]:
#compter la longueur du text
data["longueur_du_text"] = data["summary"].apply(lambda x : len(x) - x.count(" ") )
data.sample(50)

index                                              title       genre  \
2997   2997                                         Blackwater    thriller   
395     395                                  The Last Olympian     fantasy   
4190   4190  Vagabonding: An Uncommon Guide to the Art of L...      travel   
1261   1261                           Parker Pyne Investigates       crime   
4558   4558                                 His Dark Materials     fantasy   
3482   3482  Other Minds: The Octopus, the Sea, and the Dee...     science   
2345   2345                                     Halloween Rain      horror   
3921   3921                                    The Running Man    thriller   
4081   4081                                The Crucifix Killer    thriller   
1485   1485                       Dragon's Eye: A Chinese Noir       crime   
3225   3225                             Stumbling on Happiness  psychology   
4376   4376                                 From Blood and Ash     fantasy   
386     386                                  The Eternal Lover     fantasy   
2966   2966                                 The Queen's Gambit    thriller   
3769   3769                                           Triptych    thriller   
1001   1001                                 At Bertram's Hotel       crime   
353     353                           In the Green Star's Glow     fantasy   
532     532                                    The Final Nexus     science   
382     382                          Clash Of The Sky Galleons     fantasy   
2145   2145                                        Hell Island      horror   
1995   1995                             The Remains of the Day     history   
3317   3317                          An Offer From a Gentleman     romance   
3692   3692                                     Into the Water    thriller   
585     585                                     The Conspiracy     science   
410     410                                     Crown of Horns     fantasy   
3691   3691                                 One of Us Is Lying    thriller   
1778   1778                 Flashman and the Angel of the Lord     history   
3094   3094                Benjamin Franklin: An American Life     history   
3232   3232                   Civilization and Its Discontents  psychology   
1846   1846                                            Georges     history   
883     883                                           Survivor     science   
4468   4468                                         Bitterblue     fantasy   
306     306                                The Courts of Chaos     fantasy   
2821   2821                                              Topaz    thriller   
878     878                             By Heresies Distressed     science   
2727   2727                                 On Wings of Eagles    thriller   
2364   2364                                The Monstrumologist      horror   
793     793                                The Tomorrow People     science   
3093   3093  Isaac's Storm: A Man, a Time, and the Deadlies...     history   
2401   2401                                  Carpathian Castle      horror   
1208   1208                         Why Didn't They Ask Evans?       crime   
1617   1617    Scaramouche: A Romance of the French Revolution     history   
3671   3671                                     The Guest List    thriller   
4645   4645                              A Reaper at the Gates     fantasy   
3160   3160                  The Last House on Needless Street      horror   
4434   4434                                        Glass Sword     fantasy   
3409   3409                                     Fallen Too Far     romance   
4024   4024                                     Cemetery Dance    thriller   
3998   3998                                      The Forgotten    thriller   
575     575                                The Great Explosion     science   

                           

In [45]:
#Fonction pour calculer le pourcentage de ponctuation
def nombre_de_ponctuation(text):
    ponctuation = [1 for ponc in text if ponc in string.punctuation]
    resultat = sum(ponctuation)
    taille = len(text) - text.count(" ")
    return (resultat/taille)*100

In [46]:
data["pourcentage_ponctuation"] = data["summary"].apply(lambda x: nombre_de_ponctuation(x))
data.sample(50)

index                                              title     genre  \
4569   4569                                      Shadow's Edge   fantasy   
2046   2046                                     Monster Island    horror   
1456   1456                                The House of Stairs     crime   
157     157                               First Amoung Sequels   fantasy   
1451   1451                           Not the End of the World     crime   
2548   2548                               The Bourne Supremacy  thriller   
2142   2142                                        Winter Moon    horror   
2533   2533                              The Constant Gardener  thriller   
1131   1131                               Stranger in Paradise     crime   
1119   1119                        Wycliffe's Wild Goose Chase     crime   
1845   1845                             The Blithedale Romance   history   
781     781                                   Gladiator at Law   science   
1590   1590                          An Elephant for Aristotle   history   
3454   3454  The Hot Zone: The Terrifying True Story of the...   science   
923     923                                       Ann Veronica   science   
3506   3506  Are We Smart Enough to Know How Smart Animals ...   science   
545     545                                      The Cometeers   science   
772     772                                                Eon   science   
4553   4553                                     Rule of Wolves   fantasy   
484     484                                   City of the Rats   fantasy   
137     137                                           Everlost   fantasy   
326     326                           The Island of the Mighty   fantasy   
4351   4351                                            Sabriel   fantasy   
862     862                                    The Highway Men   science   
1665   1665                                     The Man Within   history   
1089   1089                                     Cover Her Face     crime   
3339   3339                                            Slammed   romance   
3177   3177                                        Slade House    horror   
3590   3590                     Seabiscuit: An American Legend    sports   
380     380                                   Soul of the Fire   fantasy   
3753   3753                                       Doctor Sleep  thriller   
2183   2183                                       Demon Theory    horror   
1226   1226                             The Lady in the Morgue     crime   
2261   2261                                      The Long Walk    horror   
182     182                            The Dragon's Apprentice   fantasy   
3022   3022      A Distant Mirror: The Calamitous 14th Century   history   
3001   3001  Guns, Germs, and Steel: The Fates of Human Soc...   history   
4248   4248                             Assassination Vacation    travel   
2058   2058                                           Duma Key    horror   
4185   4185          Neither Here nor There: Travels in Europe    travel   
1029   1029                       The Siege of Trencher's Farm     crime   
1823   1823                                   The Light Bearer   history   
1854   1854                              The Ends of the Earth   history   
3969   3969                                   The Hiding Place  thriller   
3613   3613                                         Hands Down    sports   
2475   2475                                    A Lick of Frost    horror   
254     254                              Song for the Basilisk   fantasy   
1514   1514                                       The Generals   history   
929     929                               Mission: Impractical   science   
188     188                                        The Rapture   fantasy   

                                                summary  longueur_du_text  \
4569  The second novel in the Night Angel trilogy, t

In [54]:
#foction pour nettoyer le donner
def clean_text(text):
    ponctuation = "".join([ponc for ponc in text if ponc not in string.punctuation])
    tolken = re.split("\W+",ponctuation)
    resultat = [ps.stem(mot) for mot in tolken if mot not in es_sword]
    return resultat

In [55]:
data["new_summary"] = data["summary"].apply(lambda x: clean_text(x))
data.sample(50)

index                                              title       genre  \
3351   3351                                  The Da Vinci Code     romance   
749     749                                    Diurnity's Dawn     science   
1288   1288                                              Fripp       crime   
4551   4551                                       The Diviners     fantasy   
3553   3553      The Ultimate Hitchhiker's Guide to the Galaxy     science   
1663   1663                                     A Fine Balance     history   
2145   2145                                        Hell Island      horror   
2228   2228                                             Island      horror   
1870   1870                                 The Death of Kings     history   
4514   4514                                            Redwall     fantasy   
195     195                                        Daja's Book     fantasy   
1293   1293                             Quite Ugly One Morning       crime   
2310   2310                               Circus of the Damned      horror   
3544   3544                                      Old Man's War     science   
4388   4388                                  The City of Brass     fantasy   
2882   2882                                      Cross Country    thriller   
3668   3668              The Girl Who Kicked the Hornet's Nest    thriller   
704     704                                   When Heaven Fell     science   
3541   3541                               Speaker for the Dead     science   
335     335                                    Sons of the Oak     fantasy   
3949   3949                                            Kisscut    thriller   
3991   3991                                     The Gunslinger    thriller   
3392   3392                                Memoirs of a Geisha     romance   
392     392                                     Fortune's Fool     fantasy   
3960   3960                                         The Sinner    thriller   
2789   2789                                             Impact    thriller   
4397   4397                                  A Crown of Swords     fantasy   
3227   3227     An Unquiet Mind: A Memoir of Moods and Madness  psychology   
2454   2454                             Brown Girl in the Ring      horror   
845     845                               Stopping at Slowyear     science   
3946   3946                                  The Mother-in-Law    thriller   
4136   4136                                   Imaginary Friend    thriller   
399     399                           The Once and Future King     fantasy   
2044   2044                                  A Winter Haunting      horror   
2667   2667              The Tenth Insight: Holding the Vision    thriller   
1307   1307                                   A Touch of Frost       crime   
2459   2459                               A Caress of Twilight      horror   
2224   2224                           Undead and Unappreciated      horror   
1788   1788                        The Witch of Blackbird Pond     history   
3258   3258  Attached: The New Science of Adult Attachment ...  psychology   
2600   2600       Olivia Joules and The Overactive Imagination    thriller   
2134   2134                                            Haunted      horror   
2028   2028                                   Demon Apocalypse      horror   
977     977                                           Spectrum     science   
1614   1614                              The Mauritius Command     history   
4389   4389                                    Guards! Guards!     fantasy   
4529   4529                                 Castle of Wizardry     fantasy   
652     652                                Earth Made of Glass     science   
2399   2399                                    Rosemary's Baby      horror   
74       74                                 Swords in the Mist     fantasy   

                           

In [77]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import f1_score,confusion_matrix,classification_report

In [63]:
""" c'est la qu'on vectorise le caratere summary afin d'obtenir les chiffre"""
vecteur_full = CountVectorizer(analyzer=clean_text)
vecteur_final = vecteur_full.fit_transform(data["summary"])
print(vecteur_final.shape)

(4657, 45712)


In [65]:
df = pd.concat([pd.DataFrame(vecteur_final.toarray()),data["longueur_du_text"],data["pourcentage_ponctuation"]],axis=1)
df

0  1  2  3  4  5  6  7  8  9  ...  45704  45705  45706  45707  45708  \
0     1  0  0  0  0  0  0  0  0  0  ...      0      0      0      1      0   
1     1  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
2     1  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
3     1  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
4     1  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
...  .. .. .. .. .. .. .. .. .. ..  ...    ...    ...    ...    ...    ...   
4652  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
4653  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
4654  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
4655  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
4656  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   

      45709  45710  45711  longueur_du_text  pourcentage_ponctuation  
0         0      0      0              3901                 3.537554  
1         0      0      0              2564                 3.549142  
2         0      0      0              1619                 3.767758  
3         0      0      0              3822                 3.453689  
4         0      0      0              5553                 3.097425  
...     ...    ...    ...               ...                      ...  
4652      0      0      0               748                 3.475936  
4653      0      0      0               210                 4.285714  
4654      0      0      0              1134                 3.791887  
4655      0      0      0               823                 3.523694  
4656      0      0      0               904                 1.991150  

[4657 rows x 45714 columns]

In [70]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import precision_recall_fscore_support as score

In [71]:
#donner entrainement et test
_train,x_test,y_train,y_test = train_test_split(df,data["genre"],test_size=0.2,random_state=0)

In [72]:
#model du ML
model = SVC(kernel="linear")
model.fit(x_train,y_train)
model.score(x_test,y_test)


C:\Users\HOUSSENE\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\HOUSSENE\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.6523605150214592

In [78]:
""" la obtiner notre resultat qui predit que tous les caraterique peuve t'etre predir avec plus de 50% d'exactitude les categorie de livre"""
y_predict = model.predict(x_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))


C:\Users\HOUSSENE\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


[[ 70   1   7   4   0   2   3   0  19   0]
 [  3 121  13  10   0   4  11   0   9   0]
 [  4  10  83   4   0   4   7   0  10   1]
 [  2  15  11  66   0   0   7   1  21   0]
 [  0   1   0   0  10   0   4   0   2   0]
 [  0   5   0   0   0   8   0   2   5   0]
 [  3   8  15   4   4   0  92   1   7   0]
 [  0   0   2   0   0   3   0  12   3   0]
 [ 16  10   7  10   0   2  16   0 136   0]
 [  0   0   6   2   0   1   2   0   0  10]]
              precision    recall  f1-score   support

       crime       0.71      0.66      0.69       106
     fantasy       0.71      0.71      0.71       171
     history       0.58      0.67      0.62       123
      horror       0.66      0.54      0.59       123
  psychology       0.71      0.59      0.65        17
     romance       0.33      0.40      0.36        20
     science       0.65      0.69      0.67       134
      sports       0.75      0.60      0.67        20
    thriller       0.64      0.69      0.67       197
      travel       0.91     